apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: tma-cluster
options:
  k3s:
    extraArgs:
      - arg: --tls-san=0.0.0.0
        nodeFilters:
          - server:0
servers: 1
agents: 3
ports:
  - port: 8080:8080
    nodeFilters:
      - loadbalancer
  - port: 5051:5051
    nodeFilters:
      - loadbalancer
  - port: 5052:5052
    nodeFilters:
      - loadbalancer
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 6443:6443
    nodeFilters:
      - server:0 