apiVersion: apps/v1
kind: Deployment
metadata:
  name: tma-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tma-frontend
  template:
    metadata:
      labels:
        app: tma-frontend
    spec:
      containers:
      - name: app
        image: edward1141/tma-frontend-app:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"